# Generated by Django 5.0.2 on 2024-02-25 04:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0003_alter_image_table_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="file",
            field=models.FileField(upload_to="pages"),
        ),
    ]
